name: smart-suggestion Image CI
permissions: {}

on:
  pull_request:
  push:
    branches:
    - 'beyond'

env:
  # KO_DOCKER_REPO: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/smart-suggestion
  KO_DOCKER_REPO: local/smart-suggestion

jobs:
  ci-test-and-release:
    runs-on: ${{ matrix.platform == 'linux/arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          check-latest: true
          cache: false
          go-version-file: 'go.mod'

      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9
      - run: ko build --local --platform ${{ matrix.platform }} --bare ./cmd/...

      -
        name: Smoke Test
        env:
          _TARGETARCH: ${{ matrix.platform }}
        run: |
          docker run --rm "${{ env.KO_DOCKER_REPO }}:latest" --help

          SMART_SUGGESTION_BINARY=$(
              sudo find /var/lib/docker/overlay2/ -type f -name smart-suggestion -size +2000k -print | head -n 1
          )
          RENAMED_WITH_ARCH="smart-suggestion-${_TARGETARCH//linux\//linux-}"
          sudo install -pvD "${SMART_SUGGESTION_BINARY}" "/usr/local/bin/${RENAMED_WITH_ARCH}"

          # build for darwin-arm64
          if [[ "${_TARGETARCH}" = 'linux/arm64' ]]; then
              GOOS='darwin' go build -trimpath -ldflags="-s -w" \
                  -o "/usr/local/bin/smart-suggestion-darwin-arm64" ./cmd/smart-suggestion/main.go
          fi
      -
        name: Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        if: github.event_name == 'push' && github.event.repository.default_branch == github.ref_name
        with:
          fail_on_unmatched_files: true
          generate_release_notes: false
          make_latest: true
          tag_name: latest
          files: /usr/local/bin/smart-suggestion-*
    permissions:
      contents: write
